/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class Principal extends javax.swing.JFrame {

    int AnoFIXO = 0, MesFIXO = 0, DiaFixo = 0;
    int AnoVar = 0, MesVar = 0, DiaVar = 0;
    int valSel;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setSize(998, 770);
        this.setLocationRelativeTo(null);
        iniCalendario();
        setarDias();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jSpinner1 = new javax.swing.JSpinner();
        lSem1 = new javax.swing.JLabel();
        lSem2 = new javax.swing.JLabel();
        lSem4 = new javax.swing.JLabel();
        lSem5 = new javax.swing.JLabel();
        lSem6 = new javax.swing.JLabel();
        lSem7 = new javax.swing.JLabel();
        lSem3 = new javax.swing.JLabel();
        SelecaoMes = new javax.swing.JComboBox<>();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d9 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        d13 = new javax.swing.JLabel();
        d16 = new javax.swing.JLabel();
        d23 = new javax.swing.JLabel();
        d30 = new javax.swing.JLabel();
        d37 = new javax.swing.JLabel();
        d18 = new javax.swing.JLabel();
        d25 = new javax.swing.JLabel();
        d32 = new javax.swing.JLabel();
        d39 = new javax.swing.JLabel();
        d17 = new javax.swing.JLabel();
        d24 = new javax.swing.JLabel();
        d31 = new javax.swing.JLabel();
        d38 = new javax.swing.JLabel();
        d19 = new javax.swing.JLabel();
        d26 = new javax.swing.JLabel();
        d33 = new javax.swing.JLabel();
        d40 = new javax.swing.JLabel();
        d20 = new javax.swing.JLabel();
        d27 = new javax.swing.JLabel();
        d34 = new javax.swing.JLabel();
        d41 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d14 = new javax.swing.JLabel();
        d21 = new javax.swing.JLabel();
        d28 = new javax.swing.JLabel();
        d35 = new javax.swing.JLabel();
        d42 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        d15 = new javax.swing.JLabel();
        d22 = new javax.swing.JLabel();
        d29 = new javax.swing.JLabel();
        d36 = new javax.swing.JLabel();
        SelecaoAno = new javax.swing.JComboBox<>();
        Sair = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane13 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane14 = new javax.swing.JTextPane();
        jLabel64 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextPane16 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextPane15 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextPane17 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextPane18 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextPane19 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextPane20 = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextPane21 = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextPane22 = new javax.swing.JTextPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextPane23 = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextPane24 = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextPane25 = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextPane26 = new javax.swing.JTextPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextPane27 = new javax.swing.JTextPane();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextPane28 = new javax.swing.JTextPane();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextPane29 = new javax.swing.JTextPane();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextPane30 = new javax.swing.JTextPane();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel81 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        DiaSel2 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        DiaSel = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        AnoSel1 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        AnoSel = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setFocusable(false);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        lSem1.setBackground(new java.awt.Color(102, 255, 102));
        lSem1.setForeground(new java.awt.Color(204, 0, 0));
        lSem1.setText("Dom");
        lSem1.setToolTipText("");

        lSem2.setText("Seg");

        lSem4.setText("Qua");

        lSem5.setText("Qui");

        lSem6.setText("Sex");

        lSem7.setText("Sab");

        lSem3.setText("Ter");

        SelecaoMes.setMaximumRowCount(12);
        SelecaoMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        SelecaoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoMesActionPerformed(evt);
            }
        });

        d1.setForeground(new java.awt.Color(204, 0, 0));
        d1.setText("0");

        d2.setText("0");

        d3.setText("0");

        d4.setText("0");

        d5.setText("0");

        d6.setText("0");

        d9.setText("0");

        d10.setText("0");

        d11.setText("0");

        d12.setText("0");

        d13.setText("0");

        d16.setText("0");

        d23.setText("0");

        d30.setText("0");

        d37.setText("0");

        d18.setText("0");

        d25.setText("0");

        d32.setText("0");

        d39.setText("0");

        d17.setText("0");

        d24.setText("0");

        d31.setText("0");

        d38.setText("0");

        d19.setText("0");

        d26.setText("0");

        d33.setText("0");

        d40.setText("0");

        d20.setText("0");

        d27.setText("0");

        d34.setText("0");

        d41.setText("0");

        d7.setText("0");

        d14.setText("0");

        d21.setText("0");

        d28.setText("0");

        d35.setText("0");

        d42.setText("0");

        d8.setForeground(new java.awt.Color(204, 0, 0));
        d8.setText("0");

        d15.setForeground(new java.awt.Color(204, 0, 0));
        d15.setText("0");

        d22.setForeground(new java.awt.Color(204, 0, 0));
        d22.setText("0");

        d29.setForeground(new java.awt.Color(204, 0, 0));
        d29.setText("0");

        d36.setForeground(new java.awt.Color(204, 0, 0));
        d36.setText("0");

        SelecaoAno.setEditable(true);
        SelecaoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoAnoActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lSem1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lSem2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lSem4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lSem5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lSem6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lSem7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lSem3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(SelecaoMes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(SelecaoAno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lSem1))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d1))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d8))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d15))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d22))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d29))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lSem2)
                    .addComponent(d37)
                    .addComponent(d30)
                    .addComponent(d23)
                    .addComponent(d16)
                    .addComponent(d9)
                    .addComponent(d2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lSem3))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d10)
                            .addComponent(d17)
                            .addComponent(d24)
                            .addComponent(d31)
                            .addComponent(d38))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lSem4)
                    .addComponent(d4)
                    .addComponent(d11)
                    .addComponent(d18)
                    .addComponent(d25)
                    .addComponent(d32)
                    .addComponent(d39))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lSem5)
                    .addComponent(d40, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d33, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d26, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d19, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(lSem6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lSem7))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d41)
                            .addComponent(d34)
                            .addComponent(d27)
                            .addComponent(d20)
                            .addComponent(d13)
                            .addComponent(d6))
                        .addGap(37, 37, 37)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d7)
                            .addComponent(d14)
                            .addComponent(d21)
                            .addComponent(d28)
                            .addComponent(d35)
                            .addComponent(d42))))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(SelecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SelecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSem1)
                    .addComponent(lSem2)
                    .addComponent(lSem3)
                    .addComponent(lSem4)
                    .addComponent(lSem5)
                    .addComponent(lSem6)
                    .addComponent(lSem7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1)
                    .addComponent(d2)
                    .addComponent(d3)
                    .addComponent(d4)
                    .addComponent(d5)
                    .addComponent(d6)
                    .addComponent(d7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d9)
                    .addComponent(d10)
                    .addComponent(d11)
                    .addComponent(d12)
                    .addComponent(d13)
                    .addComponent(d14)
                    .addComponent(d8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d16)
                    .addComponent(d18)
                    .addComponent(d17)
                    .addComponent(d19)
                    .addComponent(d20)
                    .addComponent(d21)
                    .addComponent(d15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d23)
                    .addComponent(d25)
                    .addComponent(d24)
                    .addComponent(d26)
                    .addComponent(d27)
                    .addComponent(d28)
                    .addComponent(d22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d30)
                    .addComponent(d32)
                    .addComponent(d31)
                    .addComponent(d33)
                    .addComponent(d34)
                    .addComponent(d35)
                    .addComponent(d29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d37)
                    .addComponent(d39)
                    .addComponent(d38)
                    .addComponent(d40)
                    .addComponent(d41)
                    .addComponent(d42)
                    .addComponent(d36)))
        );

        jLayeredPane1.add(jLayeredPane2);
        jLayeredPane2.setBounds(130, 130, 290, 190);

        Sair.setBackground(new java.awt.Color(209, 178, 47));
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/botx.jpg"))); // NOI18N
        Sair.setBorderPainted(false);
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairMouseExited(evt);
            }
        });
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Sair);
        Sair.setBounds(860, 720, 90, 40);

        jLabel54.setText("22:00");
        jLayeredPane1.add(jLabel54);
        jLabel54.setBounds(540, 625, 40, 16);
        jLabel54.getAccessibleContext().setAccessibleName("16:00");

        jLabel68.setText("21:00");
        jLayeredPane1.add(jLabel68);
        jLabel68.setBounds(540, 585, 40, 16);

        jLabel67.setText("20:00");
        jLayeredPane1.add(jLabel67);
        jLabel67.setBounds(540, 540, 40, 16);

        jLabel65.setText("18:00");
        jLayeredPane1.add(jLabel65);
        jLabel65.setBounds(540, 455, 40, 16);

        jLabel66.setText("19:00");
        jLayeredPane1.add(jLabel66);
        jLabel66.setBounds(540, 497, 40, 16);

        jLabel69.setText("8:30");
        jLayeredPane1.add(jLabel69);
        jLabel69.setBounds(740, 75, 30, 16);

        jLabel73.setText("22:30");
        jLayeredPane1.add(jLabel73);
        jLabel73.setBounds(740, 625, 40, 16);

        jLabel71.setText("11:30");
        jLayeredPane1.add(jLabel71);
        jLabel71.setBounds(740, 175, 40, 16);

        jLabel77.setText("15:30");
        jLayeredPane1.add(jLabel77);
        jLabel77.setBounds(740, 335, 40, 16);

        jLabel78.setText("16:30");
        jLayeredPane1.add(jLabel78);
        jLabel78.setBounds(740, 375, 40, 16);

        jLabel76.setText("14:30");
        jLayeredPane1.add(jLabel76);
        jLabel76.setBounds(740, 290, 40, 16);

        jLabel80.setText("18:30");
        jLayeredPane1.add(jLabel80);
        jLabel80.setBounds(740, 455, 40, 16);

        jLabel75.setText("13:30");
        jLayeredPane1.add(jLabel75);
        jLabel75.setBounds(740, 250, 40, 16);

        jLabel79.setText("17:30");
        jLayeredPane1.add(jLabel79);
        jLabel79.setBounds(740, 415, 40, 16);

        jLabel83.setText("21:30");
        jLayeredPane1.add(jLabel83);
        jLabel83.setBounds(740, 585, 40, 16);

        jLabel82.setText("20:30");
        jLayeredPane1.add(jLabel82);
        jLabel82.setBounds(740, 540, 40, 16);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFocusable(false);
        jTextPane1.setOpaque(false);
        jScrollPane1.setViewportView(jTextPane1);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(580, 110, 150, 19);

        jTextPane2.setEditable(false);
        jTextPane2.setBorder(null);
        jTextPane2.setFocusable(false);
        jTextPane2.setOpaque(false);
        jScrollPane2.setViewportView(jTextPane2);

        jLayeredPane1.add(jScrollPane2);
        jScrollPane2.setBounds(580, 70, 150, 19);

        jTextPane3.setEditable(false);
        jTextPane3.setBorder(null);
        jTextPane3.setFocusable(false);
        jTextPane3.setOpaque(false);
        jScrollPane3.setViewportView(jTextPane3);

        jLayeredPane1.add(jScrollPane3);
        jScrollPane3.setBounds(580, 140, 150, 19);

        jTextPane4.setEditable(false);
        jTextPane4.setBorder(null);
        jTextPane4.setFocusable(false);
        jTextPane4.setOpaque(false);
        jScrollPane4.setViewportView(jTextPane4);

        jLayeredPane1.add(jScrollPane4);
        jScrollPane4.setBounds(580, 180, 150, 19);

        jTextPane5.setEditable(false);
        jTextPane5.setBorder(null);
        jTextPane5.setFocusable(false);
        jTextPane5.setOpaque(false);
        jScrollPane5.setViewportView(jTextPane5);

        jLayeredPane1.add(jScrollPane5);
        jScrollPane5.setBounds(580, 210, 150, 19);

        jTextPane6.setEditable(false);
        jTextPane6.setBorder(null);
        jTextPane6.setFocusable(false);
        jTextPane6.setOpaque(false);
        jScrollPane6.setViewportView(jTextPane6);

        jLayeredPane1.add(jScrollPane6);
        jScrollPane6.setBounds(580, 250, 150, 19);

        jTextPane7.setEditable(false);
        jTextPane7.setBorder(null);
        jTextPane7.setFocusable(false);
        jTextPane7.setOpaque(false);
        jScrollPane7.setViewportView(jTextPane7);

        jLayeredPane1.add(jScrollPane7);
        jScrollPane7.setBounds(580, 290, 150, 19);

        jTextPane8.setEditable(false);
        jTextPane8.setBorder(null);
        jTextPane8.setFocusable(false);
        jTextPane8.setOpaque(false);
        jScrollPane8.setViewportView(jTextPane8);

        jLayeredPane1.add(jScrollPane8);
        jScrollPane8.setBounds(580, 330, 150, 19);

        jTextPane9.setEditable(false);
        jTextPane9.setBorder(null);
        jTextPane9.setFocusable(false);
        jTextPane9.setOpaque(false);
        jScrollPane9.setViewportView(jTextPane9);

        jLayeredPane1.add(jScrollPane9);
        jScrollPane9.setBounds(580, 380, 150, 19);

        jTextPane10.setEditable(false);
        jTextPane10.setBorder(null);
        jTextPane10.setFocusable(false);
        jTextPane10.setOpaque(false);
        jScrollPane10.setViewportView(jTextPane10);

        jLayeredPane1.add(jScrollPane10);
        jScrollPane10.setBounds(580, 410, 150, 19);

        jTextPane11.setEditable(false);
        jTextPane11.setBorder(null);
        jTextPane11.setFocusable(false);
        jTextPane11.setOpaque(false);
        jScrollPane11.setViewportView(jTextPane11);

        jLayeredPane1.add(jScrollPane11);
        jScrollPane11.setBounds(580, 450, 150, 19);

        jTextPane12.setEditable(false);
        jTextPane12.setBorder(null);
        jTextPane12.setFocusable(false);
        jTextPane12.setOpaque(false);
        jScrollPane12.setViewportView(jTextPane12);

        jLayeredPane1.add(jScrollPane12);
        jScrollPane12.setBounds(580, 500, 150, 19);

        jTextPane13.setEditable(false);
        jTextPane13.setBorder(null);
        jTextPane13.setFocusable(false);
        jTextPane13.setOpaque(false);
        jScrollPane13.setViewportView(jTextPane13);

        jLayeredPane1.add(jScrollPane13);
        jScrollPane13.setBounds(580, 540, 150, 19);

        jTextPane14.setEditable(false);
        jTextPane14.setBorder(null);
        jTextPane14.setFocusable(false);
        jTextPane14.setOpaque(false);
        jScrollPane14.setViewportView(jTextPane14);

        jLayeredPane1.add(jScrollPane14);
        jScrollPane14.setBounds(780, 70, 140, 19);

        jLabel64.setText("17:00");
        jLayeredPane1.add(jLabel64);
        jLabel64.setBounds(540, 415, 40, 16);

        jTextPane16.setEditable(false);
        jTextPane16.setBorder(null);
        jTextPane16.setFocusable(false);
        jTextPane16.setOpaque(false);
        jScrollPane16.setViewportView(jTextPane16);

        jLayeredPane1.add(jScrollPane16);
        jScrollPane16.setBounds(580, 580, 150, 19);

        jTextPane15.setEditable(false);
        jTextPane15.setBorder(null);
        jTextPane15.setFocusable(false);
        jTextPane15.setOpaque(false);
        jScrollPane15.setViewportView(jTextPane15);

        jLayeredPane1.add(jScrollPane15);
        jScrollPane15.setBounds(780, 110, 140, 19);

        jTextPane17.setEditable(false);
        jTextPane17.setBorder(null);
        jTextPane17.setFocusable(false);
        jTextPane17.setOpaque(false);
        jScrollPane17.setViewportView(jTextPane17);

        jLayeredPane1.add(jScrollPane17);
        jScrollPane17.setBounds(780, 140, 140, 19);

        jTextPane18.setEditable(false);
        jTextPane18.setBorder(null);
        jTextPane18.setFocusable(false);
        jTextPane18.setOpaque(false);
        jScrollPane18.setViewportView(jTextPane18);

        jLayeredPane1.add(jScrollPane18);
        jScrollPane18.setBounds(780, 380, 140, 19);

        jTextPane19.setEditable(false);
        jTextPane19.setBorder(null);
        jTextPane19.setFocusable(false);
        jTextPane19.setOpaque(false);
        jScrollPane19.setViewportView(jTextPane19);

        jLayeredPane1.add(jScrollPane19);
        jScrollPane19.setBounds(780, 210, 140, 19);

        jTextPane20.setEditable(false);
        jTextPane20.setBorder(null);
        jTextPane20.setFocusable(false);
        jTextPane20.setOpaque(false);
        jScrollPane20.setViewportView(jTextPane20);

        jLayeredPane1.add(jScrollPane20);
        jScrollPane20.setBounds(780, 250, 140, 19);

        jTextPane21.setEditable(false);
        jTextPane21.setBorder(null);
        jTextPane21.setFocusable(false);
        jTextPane21.setOpaque(false);
        jScrollPane21.setViewportView(jTextPane21);

        jLayeredPane1.add(jScrollPane21);
        jScrollPane21.setBounds(580, 620, 150, 19);

        jTextPane22.setEditable(false);
        jTextPane22.setBorder(null);
        jTextPane22.setFocusable(false);
        jTextPane22.setOpaque(false);
        jScrollPane22.setViewportView(jTextPane22);

        jLayeredPane1.add(jScrollPane22);
        jScrollPane22.setBounds(780, 170, 140, 19);

        jTextPane23.setEditable(false);
        jTextPane23.setBorder(null);
        jTextPane23.setFocusable(false);
        jTextPane23.setOpaque(false);
        jScrollPane23.setViewportView(jTextPane23);

        jLayeredPane1.add(jScrollPane23);
        jScrollPane23.setBounds(780, 290, 140, 19);

        jTextPane24.setEditable(false);
        jTextPane24.setBorder(null);
        jTextPane24.setFocusable(false);
        jTextPane24.setOpaque(false);
        jScrollPane24.setViewportView(jTextPane24);

        jLayeredPane1.add(jScrollPane24);
        jScrollPane24.setBounds(780, 460, 140, 19);

        jTextPane25.setEditable(false);
        jTextPane25.setBorder(null);
        jTextPane25.setFocusable(false);
        jTextPane25.setOpaque(false);
        jScrollPane25.setViewportView(jTextPane25);

        jLayeredPane1.add(jScrollPane25);
        jScrollPane25.setBounds(780, 330, 140, 19);

        jTextPane26.setEditable(false);
        jTextPane26.setBorder(null);
        jTextPane26.setFocusable(false);
        jTextPane26.setOpaque(false);
        jScrollPane26.setViewportView(jTextPane26);

        jLayeredPane1.add(jScrollPane26);
        jScrollPane26.setBounds(780, 500, 140, 19);

        jTextPane27.setEditable(false);
        jTextPane27.setBorder(null);
        jTextPane27.setFocusable(false);
        jTextPane27.setOpaque(false);
        jScrollPane27.setViewportView(jTextPane27);

        jLayeredPane1.add(jScrollPane27);
        jScrollPane27.setBounds(780, 540, 140, 19);

        jTextPane28.setEditable(false);
        jTextPane28.setBorder(null);
        jTextPane28.setFocusable(false);
        jTextPane28.setOpaque(false);
        jScrollPane28.setViewportView(jTextPane28);

        jLayeredPane1.add(jScrollPane28);
        jScrollPane28.setBounds(780, 580, 140, 19);

        jTextPane29.setEditable(false);
        jTextPane29.setBorder(null);
        jTextPane29.setFocusable(false);
        jTextPane29.setOpaque(false);
        jScrollPane29.setViewportView(jTextPane29);

        jLayeredPane1.add(jScrollPane29);
        jScrollPane29.setBounds(780, 620, 140, 19);

        jTextPane30.setEditable(false);
        jTextPane30.setBorder(null);
        jTextPane30.setFocusable(false);
        jTextPane30.setOpaque(false);
        jScrollPane30.setViewportView(jTextPane30);

        jLayeredPane1.add(jScrollPane30);
        jScrollPane30.setBounds(780, 420, 140, 19);

        jCalendar1.setBackground(new java.awt.Color(204, 102, 0));
        jCalendar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.add(jCalendar1);
        jCalendar1.setBounds(130, 340, 290, 171);

        jLabel81.setText("19:30");
        jLayeredPane1.add(jLabel81);
        jLabel81.setBounds(740, 497, 40, 16);

        jLabel74.setText("12:30");
        jLayeredPane1.add(jLabel74);
        jLabel74.setBounds(740, 210, 40, 16);

        jLabel70.setText("9:30");
        jLayeredPane1.add(jLabel70);
        jLabel70.setBounds(740, 108, 30, 16);

        jLabel63.setText("16:00");
        jLayeredPane1.add(jLabel63);
        jLabel63.setBounds(540, 375, 40, 16);

        DiaSel2.setFont(new java.awt.Font("Lobster", 1, 27)); // NOI18N
        DiaSel2.setText("1");
        DiaSel2.setToolTipText("");
        jLayeredPane1.add(DiaSel2);
        DiaSel2.setBounds(740, 40, 40, 30);

        jLabel62.setText("15:00");
        jLayeredPane1.add(jLabel62);
        jLabel62.setBounds(540, 335, 40, 16);

        DiaSel.setFont(new java.awt.Font("Lobster", 1, 27)); // NOI18N
        DiaSel.setText("Sexta");
        DiaSel.setToolTipText("");
        jLayeredPane1.add(DiaSel);
        DiaSel.setBounds(580, 40, 110, 30);

        jLabel61.setText("14:00");
        jLayeredPane1.add(jLabel61);
        jLabel61.setBounds(540, 290, 40, 16);

        AnoSel1.setFont(new java.awt.Font("Lobster", 1, 27)); // NOI18N
        AnoSel1.setText("Abril");
        AnoSel1.setToolTipText("");
        jLayeredPane1.add(AnoSel1);
        AnoSel1.setBounds(810, 40, 70, 30);

        jLabel60.setText("13:00");
        jLayeredPane1.add(jLabel60);
        jLabel60.setBounds(540, 250, 40, 16);

        jLabel72.setText("10:30");
        jLayeredPane1.add(jLabel72);
        jLabel72.setBounds(740, 140, 40, 16);

        jLabel59.setText("12:00");
        jLayeredPane1.add(jLabel59);
        jLabel59.setBounds(540, 210, 40, 16);

        jLabel58.setText("11:00");
        jLayeredPane1.add(jLabel58);
        jLabel58.setBounds(540, 175, 40, 16);

        jLabel57.setText("10:00");
        jLayeredPane1.add(jLabel57);
        jLabel57.setBounds(540, 140, 40, 16);

        jLabel56.setText("9:00");
        jLayeredPane1.add(jLabel56);
        jLabel56.setBounds(540, 108, 30, 16);

        jLabel55.setText("8:00");
        jLayeredPane1.add(jLabel55);
        jLabel55.setBounds(540, 75, 30, 16);

        jLabel53.setFont(new java.awt.Font("Lobster", 1, 50)); // NOI18N
        jLabel53.setText("Calendário");
        jLabel53.setToolTipText("");
        jLayeredPane1.add(jLabel53);
        jLabel53.setBounds(160, 60, 250, 63);

        AnoSel.setFont(new java.awt.Font("Lobster", 1, 50)); // NOI18N
        AnoSel.setText(" 2017");
        AnoSel.setToolTipText("");
        jLayeredPane1.add(AnoSel);
        AnoSel.setBounds(580, 660, 140, 50);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/backbosoksa.png"))); // NOI18N
        jLayeredPane1.add(jLabel52);
        jLabel52.setBounds(-15, -98, 1180, 970);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1041, 830);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);

    }//GEN-LAST:event_SairActionPerformed

    private void SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseExited
       Sair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_SairMouseExited

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        Sair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_SairMouseClicked

    private void SelecaoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoAnoActionPerformed
        try {
            int x = Integer.parseInt(SelecaoAno.getSelectedItem().toString());
            //DiaVar = DiaFixo;
            iniCalendario();
            AnoSel.setText(SelecaoAno.getSelectedItem().toString());
        } catch (Exception s) {
            SelecaoAno.setSelectedItem(AnoFIXO);
        }
    }//GEN-LAST:event_SelecaoAnoActionPerformed

    private void SelecaoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoMesActionPerformed
        DiaVar = DiaFixo;
        iniCalendario();
    }//GEN-LAST:event_SelecaoMesActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        valSel = Integer.parseInt(jSpinner1.getValue().toString());
        int x =SelecaoMes.getSelectedIndex();
        int ano = Integer.parseInt(SelecaoAno.getSelectedItem().toString());

        if(valSel == -1){
            if(SelecaoMes.getSelectedIndex() != 11){
                SelecaoMes.setSelectedIndex(x+1);
            }else {
                SelecaoMes.setSelectedIndex(0);
                ano = ano +1;
                SelecaoAno.setSelectedItem(ano);
            }

            if(valSel == 1){
                if(SelecaoMes.getSelectedIndex() != 0){
                    SelecaoMes.setSelectedIndex(x-1);
                }else {
                    SelecaoMes.setSelectedIndex(11);
                    ano = ano -1;
                    SelecaoAno.setSelectedItem(ano);
                }
            }
        }
        jSpinner1.setValue(0);
    }//GEN-LAST:event_jSpinner1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnoSel;
    private javax.swing.JLabel AnoSel1;
    private javax.swing.JLabel DiaSel;
    private javax.swing.JLabel DiaSel2;
    private javax.swing.JButton Sair;
    private javax.swing.JComboBox<Integer> SelecaoAno;
    private javax.swing.JComboBox<String> SelecaoMes;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d13;
    private javax.swing.JLabel d14;
    private javax.swing.JLabel d15;
    private javax.swing.JLabel d16;
    private javax.swing.JLabel d17;
    private javax.swing.JLabel d18;
    private javax.swing.JLabel d19;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d20;
    private javax.swing.JLabel d21;
    private javax.swing.JLabel d22;
    private javax.swing.JLabel d23;
    private javax.swing.JLabel d24;
    private javax.swing.JLabel d25;
    private javax.swing.JLabel d26;
    private javax.swing.JLabel d27;
    private javax.swing.JLabel d28;
    private javax.swing.JLabel d29;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d30;
    private javax.swing.JLabel d31;
    private javax.swing.JLabel d32;
    private javax.swing.JLabel d33;
    private javax.swing.JLabel d34;
    private javax.swing.JLabel d35;
    private javax.swing.JLabel d36;
    private javax.swing.JLabel d37;
    private javax.swing.JLabel d38;
    private javax.swing.JLabel d39;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d40;
    private javax.swing.JLabel d41;
    private javax.swing.JLabel d42;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane13;
    private javax.swing.JTextPane jTextPane14;
    private javax.swing.JTextPane jTextPane15;
    private javax.swing.JTextPane jTextPane16;
    private javax.swing.JTextPane jTextPane17;
    private javax.swing.JTextPane jTextPane18;
    private javax.swing.JTextPane jTextPane19;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane20;
    private javax.swing.JTextPane jTextPane21;
    private javax.swing.JTextPane jTextPane22;
    private javax.swing.JTextPane jTextPane23;
    private javax.swing.JTextPane jTextPane24;
    private javax.swing.JTextPane jTextPane25;
    private javax.swing.JTextPane jTextPane26;
    private javax.swing.JTextPane jTextPane27;
    private javax.swing.JTextPane jTextPane28;
    private javax.swing.JTextPane jTextPane29;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane30;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JLabel lSem1;
    private javax.swing.JLabel lSem2;
    private javax.swing.JLabel lSem3;
    private javax.swing.JLabel lSem4;
    private javax.swing.JLabel lSem5;
    private javax.swing.JLabel lSem6;
    private javax.swing.JLabel lSem7;
    // End of variables declaration//GEN-END:variables

//inicializa calendario
    public void iniCalendario() {
        SimpleDateFormat Ano = new SimpleDateFormat("yyyy");
        SimpleDateFormat Mes = new SimpleDateFormat("MM");
        SimpleDateFormat Dia = new SimpleDateFormat("dd");

        AnoFIXO = Integer.parseInt(Ano.format(new Date()));
        MesFIXO = Integer.parseInt(Mes.format(new Date()));
        DiaFixo = Integer.parseInt(Dia.format(new Date()));

        int AnoMaximo = AnoFIXO + 50;
        for (int i = 2010; i < AnoMaximo; i++) {
            SelecaoAno.addItem(i);
            SelecaoAno.setSelectedItem(AnoFIXO);

            if (MesFIXO == 1) {
                SelecaoMes.setSelectedIndex(0);
            }
            if (MesFIXO == 2) {
                SelecaoMes.setSelectedIndex(1);
            }
            if (MesFIXO == 3) {
                SelecaoMes.setSelectedIndex(2);
            }
            if (MesFIXO == 4) {
                SelecaoMes.setSelectedIndex(3);
            }
            if (MesFIXO == 5) {
                SelecaoMes.setSelectedIndex(4);
            }
            if (MesFIXO == 6) {
                SelecaoMes.setSelectedIndex(5);
            }
            if (MesFIXO == 7) {
                SelecaoMes.setSelectedIndex(6);
            }
            if (MesFIXO == 8) {
                SelecaoMes.setSelectedIndex(7);
            }
            if (MesFIXO == 9) {
                SelecaoMes.setSelectedIndex(8);
            }
            if (MesFIXO == 10) {
                SelecaoMes.setSelectedIndex(9);
            }
            if (MesFIXO == 11) {
                SelecaoMes.setSelectedIndex(10);
            }
            if (MesFIXO == 12) {
                SelecaoMes.setSelectedIndex(11);
            }
        }
    }

    public void setarDias() {
        d1.setText("");
        d2.setText("");
        d3.setText("");
        d4.setText("");
        d5.setText("");
        d6.setText("");
        d7.setText("");
        d8.setText("");
        d9.setText("");
        d10.setText("");
        d11.setText("");
        d12.setText("");
        d13.setText("");
        d14.setText("");
        d15.setText("");
        d16.setText("");
        d17.setText("");
        d18.setText("");
        d19.setText("");
        d20.setText("");
        d21.setText("");
        d22.setText("");
        d23.setText("");
        d24.setText("");
        d25.setText("");
        d26.setText("");
        d27.setText("");
        d28.setText("");
        d29.setText("");
        d30.setText("");
        d31.setText("");
        d32.setText("");
        d33.setText("");
        d34.setText("");
        d35.setText("");
        d36.setText("");
        d37.setText("");
        d38.setText("");
        d39.setText("");
        d40.setText("");
        d41.setText("");
        d42.setText("");

        
        MesVar = SelecaoMes.getSelectedIndex();
        AnoVar = Integer.parseInt(SelecaoAno.getSelectedItem().toString());
        DiaVar = DiaFixo;
        int TotalDiaMes = 0;

        if (MesVar == 0) {
            TotalDiaMes = 31;
        } else if (MesVar == 1) {
            int resultado = (AnoVar % 4);
            if (resultado == 0) {
                TotalDiaMes = 29;
            } else {
                TotalDiaMes = 28;
            }
        } else if (MesVar == 2) {
            TotalDiaMes = 31;
        } else if (MesVar == 3) {
            TotalDiaMes = 30;
        } else if (MesVar == 4) {
            TotalDiaMes = 31;
        } else if (MesVar == 5) {
            TotalDiaMes = 30;
        } else if (MesVar == 6) {
            TotalDiaMes = 31;
        } else if (MesVar == 7) {
            TotalDiaMes = 31;
        } else if (MesVar == 8) {
            TotalDiaMes = 30;
        } else if (MesVar == 9) {
            TotalDiaMes = 31;
        } else if (MesVar == 10) {
            TotalDiaMes = 30;
        } else if (MesVar == 11) {
            TotalDiaMes = 31;
        }

        Calendar calendar = new Calendar() {
            @Override
            protected void computeTime() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            protected void computeFields() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void add(int field, int amount) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void roll(int field, boolean up) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getMinimum(int field) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getMaximum(int field) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getGreatestMinimum(int field) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getLeastMaximum(int field) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        calendar = Calendar.getInstance();
        calendar.set(AnoVar, MesVar, 1);
        int setaDia = 0;

        int semana = calendar.get(Calendar.DAY_OF_WEEK);
        if (semana == Calendar.SUNDAY) {
            setaDia = 1;
        } else if (semana == Calendar.MONDAY) {
            setaDia = 2;
        } else if (semana == Calendar.TUESDAY) {
            setaDia = 3;
        } else if (semana == Calendar.WEDNESDAY) {
            setaDia = 4;
        } else if (semana == Calendar.THURSDAY) {
            setaDia = 5;
        } else if (semana == Calendar.FRIDAY) {
            setaDia = 6;
        } else if (semana == Calendar.SATURDAY) {
            setaDia = 7;
        }

        for (int i = 1; i <= TotalDiaMes; i++) {
            switch (setaDia) {
                case 1:
                    d1.setText("" + i);
                    break;
                case 2:
                    d2.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d2.setForeground(Color.red);
                    } else {
                        d3.setForeground(Color.black);
                    }
                    break;
                case 3:
                    d3.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d3.setForeground(Color.red);
                    } else {
                        d3.setForeground(Color.black);
                    }
                    break;
                case 4:
                    d4.setText("" + i);
                    if (i == DiaFixo && MesVar == -1 && AnoVar == AnoFIXO) {
                        d4.setForeground(Color.red);
                    } else {
                        d4.setForeground(Color.black);
                    }
                    break;
                case 5:
                    d5.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d5.setForeground(Color.red);
                    } else {
                        d5.setForeground(Color.black);
                    }
                    break;
                case 6:
                    d6.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d6.setForeground(Color.red);
                    } else {
                        d6.setForeground(Color.black);
                    }
                    break;
                case 7:
                    d7.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d7.setForeground(Color.red);
                    } else {
                        d7.setForeground(Color.black);
                    }
                    break;
                case 8:
                    d8.setText("" + i);
                    break;
                case 9:
                    d9.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d9.setForeground(Color.red);
                    } else {
                        d9.setForeground(Color.black);
                    }
                    break;
                case 10:
                    d10.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d10.setForeground(Color.red);
                    } else {
                        d10.setForeground(Color.black);
                    }
                    break;
                case 11:
                    d11.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d11.setForeground(Color.red);
                    } else {
                        d11.setForeground(Color.black);
                    }
                    break;
                case 12:
                    d12.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d12.setForeground(Color.red);
                    } else {
                        d12.setForeground(Color.black);
                    }
                    break;
                case 13:
                    d13.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d13.setForeground(Color.red);
                    } else {
                        d13.setForeground(Color.black);
                    }
                    break;
                case 14:
                    d14.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d14.setForeground(Color.red);
                    } else {
                        d14.setForeground(Color.black);
                    }
                    break;
                case 15:
                    d15.setText("" + i);
                    break;
                case 16:
                    d16.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d16.setForeground(Color.red);
                    } else {
                        d16.setForeground(Color.black);
                    }
                    break;
                case 17:
                    d17.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d17.setForeground(Color.red);
                    } else {
                        d17.setForeground(Color.black);
                    }
                    break;
                case 18:
                    d18.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d18.setForeground(Color.red);
                    } else {
                        d18.setForeground(Color.black);
                    }
                    break;
                case 19:
                    d19.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d19.setForeground(Color.red);
                    } else {
                        d19.setForeground(Color.black);
                    }
                    break;
                case 20:
                    d20.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d20.setForeground(Color.red);
                    } else {
                        d20.setForeground(Color.black);
                    }
                    break;
                case 21:
                    d21.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d21.setForeground(Color.red);
                    } else {
                        d21.setForeground(Color.black);
                    }
                    break;
                case 22:
                    d22.setText("" + i);
                    break;
                case 23:
                    d23.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d23.setForeground(Color.red);
                    } else {
                        d23.setForeground(Color.black);
                    }
                    break;
                case 24:
                    d24.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d24.setForeground(Color.red);
                    } else {
                        d24.setForeground(Color.black);
                    }
                    break;
                case 25:
                    d25.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d25.setForeground(Color.red);
                    } else {
                        d25.setForeground(Color.black);
                    }
                    break;
                case 26:
                    d26.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d26.setForeground(Color.red);
                    } else {
                        d26.setForeground(Color.black);
                    }
                    break;
                case 27:
                    d27.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d27.setForeground(Color.red);
                    } else {
                        d27.setForeground(Color.black);
                    }
                    break;
                case 28:
                    d28.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d28.setForeground(Color.red);
                    } else {
                        d28.setForeground(Color.black);
                    }
                    break;
                case 29:
                    d29.setText("" + i);
                    break;
                case 30:
                    d30.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d30.setForeground(Color.red);
                    } else {
                        d30.setForeground(Color.black);
                    }
                    break;
                case 31:
                    d31.setText("" + i);
                    if (i == DiaFixo & MesVar == -1 & AnoVar == AnoFIXO) {
                        d31.setForeground(Color.red);
                    } else {
                        d31.setForeground(Color.black);
                    }
                    break;
                case 32:
                    d32.setText("" + i);
                    break;
                case 33:
                    d33.setText("" + i);
                    break;
                case 34:
                    d34.setText("" + i);
                    break;
                case 35:
                    d35.setText("" + i);
                    break;
                case 36:
                    d24.setText("" + i);
                    break;
                case 37:
                    d37.setText("" + i);
                    break;
                case 38:
                    d38.setText("" + i);
                    break;
                case 39:
                    d39.setText("" + i);
                    break;
                case 40:
                    d40.setText("" + i);
                    break;
                case 41:
                    d41.setText("" + i);
                    break;
                case 42:
                    d42.setText("" + i);
                    break;
            }
            setaDia++;
        }

    }

}
